name: Dev Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMG_REGISTRY_HOST: quay.io
  IMG_REGISTRY_ORG: kuadrant
  IMG_REGISTRY_REPO: console-plugin

jobs:
  build:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Mock image build
        run: |
          echo "Mocking the image builds"

      - name: Sleep for x seconds
        run: sleep 10
