name: E2E Tests

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  e2e-rbac:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Mock e2e-rbac
        run: |
          echo "Mocking the e2e rbac"

      - name: Sleep for x seconds
        run: sleep 10
