name: I18n Check

on:
  pull_request:
    branches:
      - '**'
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  i18n:
    runs-on: ubuntu-latest

    steps:
      - name: Mock i18n
        run: |
          echo "Mocking the i18n"

      - name: Sleep for x seconds
        run: sleep 10
