name: Add issues to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    # Only run jobs if the feature branch is in your repo (not in a fork)
    # OR
    # it is an issue
    if: github.event.pull_request.head.repo.full_name == github.repository || github.event.issue.number != ''
    runs-on: ubuntu-latest
    steps:
      - name: Mock add to project
        run: |
          echo "Mocking add-to-project"

      - name: Sleep for x seconds
        run: sleep 10
