name: Lint Check

on:
  pull_request:
    branches:
      - '**'
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Mock lint
        run: |
          echo "Mocking the lint"

      - name: Sleep for x seconds
        run: sleep 10
