name: Release Build and Push

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  IMAGE_BASE_NAME: kuadrant/console-plugin
  REGISTRY: quay.io

jobs:
  build:
    name: Release Build and Push Multi-Arch Image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Mock release build and push multi-arch image
        run: |
          echo "Mocking the release build and push multi-arch image"

      - name: Sleep for x seconds
        run: sleep 10

